# Laboratorio 4

## Inteligencia Artificial

### Andres de la Roca 20332

In [52]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from utility_funcs import logistic_regression, sigmoid

### Task 1.1
Leer el archivo CSV proporcionado y almacenarlo en un np.array para ser trabajado en el notebook.

In [53]:
data = pd.read_csv('framingham.csv')

In [54]:
data

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [55]:
data_array = data.values

In [56]:
data_array

array([[  1.,  39.,   4., ...,  80.,  77.,   0.],
       [  0.,  46.,   2., ...,  95.,  76.,   0.],
       [  1.,  48.,   1., ...,  75.,  70.,   0.],
       ...,
       [  0.,  48.,   2., ...,  84.,  86.,   0.],
       [  0.,  44.,   1., ...,  86.,  nan,   0.],
       [  0.,  52.,   2., ...,  80., 107.,   0.]])

### Task 1.2
Ajustar un modelo logístico polinomial en base al juego de datos cargado de forma matricial que relaciona las variables independientes que usted considere apropiadas (puede no utilizar todas las componentes de X), con la variable dependiente de salida (sufre o no sufre un paro cardíaco).

In [57]:
# Componentes de X
X = data_array[:, 9:13]
# X = np.c_[np.ones(X.shape[0]), X] # Para la interceptacion del modelo

In [63]:
X

array([[195.  , 106.  ,  70.  ,  26.97],
       [250.  , 121.  ,  81.  ,  28.73],
       [245.  , 127.5 ,  80.  ,  25.34],
       ...,
       [248.  , 131.  ,  72.  ,  22.  ],
       [210.  , 126.5 ,  87.  ,  19.16],
       [269.  , 133.5 ,  83.  ,  21.47]])

In [59]:
# Variable de salida
y = data_array[:, 6]

In [60]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [61]:
theta = logistic_regression(X, y, 2)

LinAlgError: Singular matrix

### Task 1.3
Utilice la implementación vectorial del algoritmo de regresión logística (descenso del gradiente visto en clase).


### Task 1.4
Usando cross-validation determine el grado del polinomio que mejor describe la nube de puntos (encuentre el mejor balance entre apego a los datos de entrenamiento y generalización para datos previamente no observados).

### Task 1.5 - Hallazgos

hola